### ISSUE TITLE
Создание/Редактирование проекта: проект сохраняется при пустом обязательном поле "Описание"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#10]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Проекты"
2.В списке проектов нажать на кнопку "Добавить"/ "Изменить"
3.В форме создание/редактирование проекта заполнить все поля, кроме поля "Описание"
4.Нажать на кнопку "Сохранить"

**Получено:**
Проект сохраняется
https://user-images.githubusercontent.com/88539537/205861975-6a115887-6437-4bd3-a09c-4bd2464a44e0.mp4
**Ожидаемо:**
Появление валидационного сообщения "Описание не должно быть меньше 10 и больше 255 символов". Минимальное количество символов для заполнения поля - 10. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
Страйся формулировать без "не", не заполнении=пустом
