### ISSUE TITLE
Создание/Редактирование задачи: неверный порядок расположения полей

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#16]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Задачи"
2.В списке задач нажать на кнопку "Добавить"/"Изменить"
3.В форме создание/редактирование задачи обратить внимание на порядок расположения полей

**Получено:**
Отображается:

Идентификатор
Название
Работа
Дата начала
Дата окончания
Статус
Исполнитель
Проект

**Ожидаемо:**

Идентификатор
Проект
Название
Работа
Дата начала
Дата окончания
Статус
Исполнитель
![Screenshot_1](https://user-images.githubusercontent.com/88539537/205877947-77ca8a43-dba8-4d20-9756-3e603c0a6074.png)
Смотреть спецификацию п.6 "Форма ввода задачи"

**Comment by VKozlovskaya** [comment]
ссылку на спецификацию необходимо указывать после описания ОР
