### ISSUE TITLE
Создание/Редактирование Проекта/Задачи/Персоны: ошибка при сохранении значения с символом "Ё" в текстовом поле

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#17]
**Актуально** для: 
- формы ввода задачи (поле - название); 
- формы ввода персоны (поля - фамилия, имя, отчество, должность);
-  формы проекта (все поля).

**Шаги воспроизведения:**

1. В главном меню нажать на кнопку "Проекты"
2. В списке проектов нажать на кнопку "Добавить"/"Изменить"
3. В форме создание/редактирование проекта заполнить все поля
4. В каждое поле ввести данные с символом Ё
5. Нажать кнопку "Сохранить"

**Получено:**
Отображается валидационное сообщение. Поля не сохраняют символ Ё

**Ожидаемо:**
Поля сохраняют символ Ё

Требование оговорено с куратором.

https://user-images.githubusercontent.com/88539537/205882436-e655bc15-391c-4913-a21d-c14a98949a72.mp4

**Comment by VKozlovskaya** [comment]
- текст "Форма ввода проекта:" перед шагами является избыточным
- актуальность дефекта предлагаю вынести перед описанием шагов и выделить жирным слово "актуально", весь текст выделять не стоит
- заголовок можно переформулировать без "не": ошибка при сохранении значения с символом "Ё" в текстовом поле
- в "получено" лучше прописывать, что происходит: отображается валид. сообщение

**Comment by VKozlovskaya** [comment]
- Шаг 4: переформулировать в такой же форме, как прерыдущие шаги. Т.е. что нужно сделать
- зачем дублируется актуальности в получено/ожидаемо?

**Comment by VKozlovskaya** [comment]
зачем дублируется актуальности в получено/ожидаемо? -- **не исправлено**
