### ISSUE TITLE
Создание/Редактирование персоны: неверное максимальное количество символов в валидационном сообщении в поле "Должность"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#19]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Персоны"
2.В списке персон нажать на кнопку "Добавить"/"Изменить"
3.Ввести 31 символ в поле должность
4.В форме создание/редактирование персоны нажать на кнопку "Сохранить"
5.Обратить внимание на максимально введенное "Количество символов" в поле должность

**Получено:**
Поле "Должность" не сохраняет более 30 символов.

**Ожидаемо:**
Поле "Должность" не сохраняет более 50 символов. Требование оговорено с куратором.
![sdv](https://user-images.githubusercontent.com/88539537/205896817-1fe851ae-3349-45bd-a183-5cc34b467f93.png)

**Comment by VKozlovskaya** [comment]
почему неверное минимальное кол-во? И там, и там прописано 2

**Comment by VKozlovskaya** [comment]
Не согласован шаг 5 и прописанные результаты (в шаге говорится о валидационном сообщении, а в результатах о самом поле)

**Comment by VKozlovskaya** [comment]
Рекомендую прописывать, что происходит с записью. Т.е. вместо "поле принимает" прописывать " запись сохранилась", а вместо "не принимает" - "отображается валидационное сообщение"
