### ISSUE TITLE
Создание/Редактирование персоны: неверное допустимое максимальное количество символов в поле "Должность"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#23]
**Шаги воспроизведения:**

1. В главном меню нажать на кнопку "Персоны"
2. В списке персон нажать на кнопку "Добавить"/"Изменить"
3. Ввести 50 символов в поле "Должность"
4. Нажать сохранить

**Получено**:
Появится валидационное сообщение "Должность не может быть меньше 2 и больше 30 символов"

**Ожидаемо:**
Количество максимальных символов для ввода в поле должность не должно превышать 50 символов. Требование оговорено с куратором
![bbbbb](https://user-images.githubusercontent.com/88539537/205901028-cb0d5c97-900d-4fde-a80d-3dc8e405b180.png)

**Comment by VKozlovskaya** [comment]
попробуй
