### ISSUE TITLE
Создание/Редактирование задачи: выбор исполнителя происходит из формы задачи

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#24]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Задачи"
2.В списке задач нажать на кнопку "Добавить"/"Изменить"
3.В форме создание создание/редактирование задачи обратить внимание на список исполнителей

**Получено:**
Исполнители отображены на форме, в списке с чек-боксами

**Ожидаемо:**
Исполнители должны отображаться в выпадающем списке. Требование оговорено с куратором

![spis](https://user-images.githubusercontent.com/88539537/205902395-d50f2bb5-969d-4b7c-a317-14f40d647691.png)

**Comment by VKozlovskaya** [comment]
- "все возможные" избыточный текст в Получено/Ожидаемо
- заголовок можно переформулировать. Сейчас из него следует, что я не могу выбрать исполнителя

**Comment by VKozlovskaya** [comment]
- Неверно прописан ПР: при оформлении дефекта нужно удалять(не прописывать) слова, которые не несут ценности. Исполнители не "просто" отображаются на форме, в списке с чек-боксами.
