### ISSUE TITLE
Удаление сотрудника: доступно удаление единственного исполнителя

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#28]
**Шаги воспроизведения:**

**Предусловие**: создан проект и единственный исполнитель
1.В главном меню нажать на кнопку "Задачи"
2.В списке задач заполнить все поля и выбрать уже созданного исполнителя
3.Нажать на кнопку "Сохранить"
4.Перейти во вкладку "Персоны"
5.Удалить сотрудника, который был указан в п.2

**Получено:**
Пользователь может удалить единственного сотрудника в задаче

https://user-images.githubusercontent.com/88539537/206400295-b7f23521-32f1-436f-af7a-b143b379ce45.mp4

**Ожидаемо:**
Пользователь не может удалить единственного сотрудника в задаче. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
- заголовок можно сократить до "Редактирование задачи: доступно удаление единственного исполнителя"
- в шаге 5 отсутствует запятая

**Comment by VKozlovskaya** [comment]
- Слово "заранее" в предусловии избыточно. 
- прописать, что создан именно "единственный" сотрудник нужно в предуловии, для этого оно и есть. Дублировать в шагах не нужно
