### ISSUE TITLE
 Создание/Редактирование проекта: сохранение проекта с недопустимыми символомами ;@"%:?&.*, в поле "Название"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#29]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Проекты"
2.В списке проектов нажать на кнопку "Добавить"/"Изменить"
3.В форме создание/редактирование проекта заполнить поле "Название" спецсимволами ;@"%:?&.*,
4.Заполнить все остальные обязательные поля
5.Нажать кнопку "Сохранить"

**Получено:**
Разрешен ввод и сохранение недопустимых спец.символов ;@"%:?&.*, в поле название
![SpecSymbls](https://user-images.githubusercontent.com/88539537/206403226-ebc779e0-158b-4b8d-920b-c0cf156316b8.png)

**Ожидаемо:**
Запрещен ввод и сохранение недопустимых спец.символов ;@"%:?&.*, в поле название См. спецификацию П.5 "Форма ввода задачи"

**Comment by VKozlovskaya** [comment]
- 6 шаг некорректно прописан. Нельзя сохранить запись с недопустимыми символами.
- в заголовке отсутствует суть-ввод допустим или нет? Можно переорганизовать заголовок след.образом: Создание/Редактирование проекта. Поле "Название": допустим ввод недопустимых символов ;@"%:?&.*,

**Comment by VKozlovskaya** [comment]
- неверно прописан последний шаг
- неверно прописан ОР: разрешен не только ввод, но и сохранение

**Comment by Aliaksei3** [comment]
Предположу, что будет лучше без 6 пункта (немного изменил ПР и ОР)
