### ISSUE TITLE
Создание/Редактирование проекта: недопустимо сохранение спец.символа ! в поле "Описание"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#31]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Проекты"
2.В списке проектов нажать на кнопку "Добавить"/"Изменить"
3.В поле "Описание" ввести спец. символ !
4.Заполнить все остальные обязательные поля
5.Нажать кнопку "Сохранить"

**Получено:**
Поле "Описание" не принимает спец.символ !
![ProjectSymbol](https://user-images.githubusercontent.com/88539537/206405409-f78dce70-744d-452d-94f1-86e8e06a6b50.png)

**Ожидаемо:**
Поле "Описание" должно принимать спец.символ ! Проект создается. См. спецификацию П.5 "Форма ввода проекта"

**Comment by VKozlovskaya** [comment]
см. комментарий к дефекту 32

**Comment by VKozlovskaya** [comment]
шаг 6 не согласуется с ОР
