### ISSUE TITLE
Создание/Редактирование проекта:допустимо сохранение недопустимых спецсимволов @;%: &*" в поле "Описание"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#32]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Проекты"
2.В списке проектов нажать на кнопку "Добавить"/"Изменить"
3.В поле "Описание" ввести спец. символы @;%: &*"
4.Заполнить все остальные обязательные поля
5.Нажать кнопку "Сохранить"

**Получено:**
Разрешен ввод и сохранение недопустимых спец.символов @;%: &*" в поле описание
![ProjectDescription](https://user-images.githubusercontent.com/88539537/206406457-1d4e1d71-98f5-4a19-92f6-b3af739bf3ea.png)

**Ожидаемо:**
Запрещен ввод и сохранение недопустимых спец.символов @;%: &*" в поле описание См. спецификацию П.5 "Форма ввода проекта"

**Comment by VKozlovskaya** [comment]
- В заголовке можно прописать как "допустимо сохранение недопустимых спецсимволов" +их перечисление
- В "Ожидаемо" можно прописать как "Отображение валидационного сообщения, проект не создался"
- Ссылаться на договоренности с кураторм/заказчиком можно в дефектах, для которых нет спецификации (не прописано поведение, например). Допустимые для ввода и сохранения символы прописаны явно в спецификации, необходимо сослаться на них

**Comment by VKozlovskaya** [comment]
неверно прописан последний шаг

**Comment by Aliaksei3** [comment]
Предположу, что будет лучше без 6 пункта (немного изменил ПР и ОР)
