### ISSUE TITLE
Создание/Редактирование задачи: данные сохраняются при вводе и сохранении недопустимых спец.символов в поле "Название"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#33]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Задачи"
2.В списке задач нажать на кнопку "Добавить"/"Изменить"
3.В форме создание/редактирование задачи ввести недопустимые спец.символы @;%:&*" в поле "Название"
4.Заполнить все обязательные поля
5.Нажать на кнопку "Сохранить"

**Получено:**
Разрешен ввод и сохранение недопустимых спец.символов @;%:&*" в поле название
![Task_Symbols](https://user-images.githubusercontent.com/88539537/206409105-7f94e520-0807-4268-8175-b89d3047bdba.png)

**Ожидаемо:**
Запрещен ввод и сохранение недопустимых спец.символов @;%:&*" в поле название См. спецификацию П.6 "Форма ввода задачи"

**Comment by VKozlovskaya** [comment]
- дублируется текст в заголовке, шаге 3
- опечатка в заголовке
- не совсем понятен шаг 6. Если эти символы недопустимы для ввода и сохранения, то запись с ними не сохранится
- требование о допустимых символах согласовано в спецификации. Необходимо ссылаться на документ с требованиями (конкретный пункт)

**Comment by VKozlovskaya** [comment]
Не исправлено: 

- не совсем понятен шаг 6. Если эти символы недопустимы для ввода и сохранения, то запись с ними не сохранится

**Comment by Aliaksei3** [comment]
Предположу, что будет лучше без 6 пункта (немного изменил ПР и ОР)
