### ISSUE TITLE
Создание/Редактирование задачи: выпадающий список в поле "Статус" содержит лишний пункт

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#34]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Задачи"
2.В списке задач нажать на кнопку "Добавить"/"Изменить"
3.В форме создание задачи обратить внимание на поле "Статус"

**Получено:**
В выпадающем списке отображается лишний пункт "Выберите статус".
![Status](https://user-images.githubusercontent.com/88539537/206410453-6f37b603-087e-4a4f-b7ae-52e6b31cbcc1.png)

**Ожидаемо:**
В выпадающем списке должны быть только наименования статусов. См п.3 "Форма ввода задачи"

**Comment by VKozlovskaya** [comment]
см. комментарии к дефекту [40](https://github.com/Aliaksei3/Qulix/issues/40)

**Comment by Aliaksei3** [comment]
судя по комментарию к дефекту 40, тут все окей.

**Comment by VKozlovskaya** [comment]
суть дефекта в том, что отображается лишний текст в выпадающем списке

**Comment by VKozlovskaya** [comment]
какой именно лишний текст?
