### ISSUE TITLE
Главное меню: можно кликнуть на кнопку за её пределами и перейти в выбранный раздел меню

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#37]
**Шаги воспроизведения:**

1. Перейти в главное меню
2. Кликать на проекты/задачи/персоны за пределами границы

**Получаемо:**
Пользователь может перейти на выбранную вкладку за пределами границы

https://user-images.githubusercontent.com/88539537/206421879-1e9295da-77da-4182-944e-4808e9fcd582.mp4

**Ожидаемо:**
Пользователь не может перейти на выбранную вкладку за пределами границы. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
опечатка в заголовке

**Comment by VKozlovskaya** [comment]
неверно прописан ожидаемый результат
