### ISSUE TITLE
Создание/Редактирование задачи: выпадающий список поля "Проект" содержит лишний пункт

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#40]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Задачи"
2.В списке задач нажать на кнопку "Добавить"/"Изменить"
3.Открыть выпадающий список проектов
4.Обратить внимание на запись "Выберите проект"

**Получаемо:**
В выпадающем списке отображается лишний пункт "Выберите проект".
![Choose Project](https://user-images.githubusercontent.com/88539537/206426174-9d571f81-1c50-4522-be30-d4a855ff321b.png)

**Ожидаемо:**
В выпадающем списке должны отображаться только проекты. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
Заголовок дефекта должен отображать суть дефекта. Здесь это-отображение текста "Выберите проект" в выпадающем списке с проектами

**Comment by VKozlovskaya** [comment]
суть дефекта в том, что отображается лишний текст в выпадающем списке

**Comment by VKozlovskaya** [comment]
Необходимо переформулировать заголовок и ПР. См. комментарий выше и пропиши КОРРЕКТНО
