### ISSUE TITLE
Создание/редактирование проекта/задачи/персоны: запретить возможность каких-либо взаимодействий с записью, которая уже удалена

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#41]
**Шаги воспроизведения:**
Предусловие: открыты по две вкладки проекты/задачи/персоны; записи в этих вкладках уже созданы
1. Открыть форму редактирования проекта/задачи/персоны в первой вкладке
2. Кликнуть на кнопку изменить в каждой вкладке для созданной записи
3. Открыть список проектов/задач персон
4. Открытые записи, которые были открыты в первых вкладках удалить
5. Перейти к вкладкам редактирования проектов/задач/персон и нажать "Сохранить"

**Получено:** 
Пользователь перейдет на отображение формы проектов/задач/персон

https://user-images.githubusercontent.com/88539537/206432016-abd4097a-d6a0-4ab2-b249-e7522b9ffbe7.mp4

**Ожидаемо:**
Пользователь получит валидационное сообщение "Проект/задача/персона была удалена". Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
ошибка в заголовке

**Comment by VKozlovskaya** [comment]
Предыдущий комментарий актуален
