### ISSUE TITLE
Создание/редактирование проектов/задач/персон: сохранение невалидных данных в полях после перезагрузки страницы

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#42]
**Шаги воспроизведения:**

1. Открыть форму редактирования проекта/задачи/персоны 
2. Заполнить поля невалидными данными
3. Нажать кнопку "Сохранить"
4. Перезагрузить страницу
5. Обратить внимание на сохраненные данные

**Получено:**
Данные остаются.

https://user-images.githubusercontent.com/88539537/206434563-6ef84c74-3a52-40e3-aa46-0b4f653c2834.mp4

**Ожидаемо:**
Данные в полях должны быть очищены. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
- запятая в заголовке не нужна
- опечатка в описании шагов дефекта
