### ISSUE TITLE
Отображение/создание/редактирование проектов/задач/персон: пользователь имеет возможность многократного нажатия на кнопки

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#45]
**Шаги воспроизведения:**

1. На форме отображения проектов/задач/персон много раз подряд кликать на кнопки "Изменить/Удалить"
2. На форме добавления проекта - много раз подряд кликать на кнопку "Добавить задачу"
3. На форме задачи - много раз подряд кликать на кнопку "Добавить"
4. На форме добавления проектов/задач/персон - много раз подряд кликать на кнопки "Сохранить"

**Получено:**
1. Форма отображения проектов/задач/персон - разрешено многократное нажатие на кнопки "изменить/удалить", на форме задачи - разрешено многократное нажатие на кнопку "Добавить"
5. Форма добавления проектов/задач/персон - разрешено многократное нажати на кнопки "Сохранить"
6. Форма добавления проектов - разрешено многократное нажати на кнопку "Добавить задачу"

https://user-images.githubusercontent.com/88539537/206438555-6a06cab0-5677-41a2-85cf-dd006d9af66e.mp4

**Ожидаемо:**
Пользователь не должен иметь возможность многократного нажатия на кнопки. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
``
