### ISSUE TITLE
Создание/редактирование проекта: допустимо создание двух проектов с одинаковыми сокращенными названиями

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#50]
**Шаги воспроизведения:**

1. Открыть форму создания проекта
2. Заполнить все поля (запомнить, какие данные были заполнены в поле сокращенное название)
3. Нажать кнопку "Сохранить"
4. Открыть форму создания/изменения проекта
5. Заполнить все обязательные поля
6. Сокращенное название указать такое же, как в предыдущем проекте
7. Нажать кнопку "Сохранить" 

**Получено:**

https://user-images.githubusercontent.com/88539537/206448118-6352c9f7-2df1-4040-a72a-e61e2731439f.mp4

Допустимо создание двух проектов с одинаковым сокращенным названием. Не появляется валидационного сообщения о том, что проект с таким сокращённым названием уже существует.
**Ожидаемо:**

Невозможность создания двух проектов с одинаковым сокращенным названием.Появляется валидационное сообщение о том, что проект с таким сокращённым названием уже существует.

**Comment by VKozlovskaya** [comment]
проблема заключается в том, что допустимо создание двух проектов с одинаковыми сокращенными названиями, а не в отсутствии валид. сообщений

**Comment by VKozlovskaya** [comment]
заголовок недостаточно точный. Необходимо уточнить, что "допустимо" создание
