### ISSUE TITLE
Создание/Редактирование задачи: очищается поле "Исполнитель" при вводе невалидных данных в другие поля

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#51]
**Шаги воспроизведения:**

1. Открыть форму добавления/редактирования задачи
2. Заполнить все поля и выбрать исполнителя
3. В одном из полей ввести невалидные данные
4. Нажать кнопку "Сохранить"
5. После появления валидационного сообщения обратить внимание на поле исполнитель

**Получено:**

https://user-images.githubusercontent.com/88539537/206460540-aeeef81f-8cc2-4132-9d23-480928e24da8.mp4

Поле исполнитель очищается.
**Ожидаемо:**

Выбранное ранее значение остается.

**Comment by VKozlovskaya** [comment]
- в получено/ожидаемо избыточно прописывать "После появления валидационного сообщения" это прописано в шагах
- желательно, прописывать все без отрицания. Например, ожидаемый результат можно прописать "выбранное ранее значение остается" (или любая другая аналогичная формулировка без "не")
- в ОР опечатка

**Comment by VKozlovskaya** [comment]
я бы переформулировала заголовок в "Создание/Редактирование задачи: очищается поле "Исполнитель" при вводе невалидных данных в другие поля"
при соствлении заголовка дефекта можешь подставлять вопросы "что? где? когда?"
