### ISSUE TITLE
Редактирование задачи: пропадает исполнитель при открытии формы редактирования задачи

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#52]
**Шаги воспроизведения:**
Предусловие: создать задачу, заполнив все поля
1. Перейти на форму список задач
2. Обратить внимание на то, что колонка исполнитель заполнена
3. Нажать на кнопку "Изменить" в этой записи
4. Обратить внимание на исполнителя, в режиме редактирования

**Получено:**
Исполнитель пропадает.

https://user-images.githubusercontent.com/88539537/206461649-4cf95538-c695-44e4-8369-9992b9b75127.mp4

**Ожидаемо:**
Выбранное ранее значение остается.

**Comment by VKozlovskaya** [comment]
- в получено/ожидаемо избыточно прописывать "после того, как пользователь переходит в режим редактирования" это прописано в шагах
- Получено/ожидаемо не выделено жирным
