### ISSUE TITLE
Создание/Редактирование проекта/задачи/персоны: в полях обрезаются пробелы по бокам и между слов

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#53]
**Актуально** для:
- формы задачи (поле Название);
- формы персоны (поле должность);
- формы проекта (все поля).

**Шаги по воспроизведению:**

1. Открыть форму создания/ редактирования проекта
2. Заполнить все поля данными, в которых присутствует несколько пробелов перед первым символом, после последнего символа, между символами.
3. Нажать на кнопку "Сохранить"

**Получено:**
Пробелы обрезаются по бокам и между символами

https://user-images.githubusercontent.com/88539537/206463186-12e00cd9-c92a-4aef-b9fc-c48ff18e6707.mp4

**Ожидаемо:**
Пробелы не должны обрезаться по бокам и между символами. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
Шаги вопроизведения аналогичны (отличаются лишь формы и поля), для уменьшения описания дефекта можно прописать для каких форм/полей актуален данный дефект и напримере одной формы/поля прописать шаги

**Comment by VKozlovskaya** [comment]
- "форма проекта" избыточна после слов "шаги воспроизведения
- в заголовке последнее слово не в той форме
- актуальность следует вынести в начало дефекта и выделить жирным

**Comment by VKozlovskaya** [comment]
- в заголовке последнее слово не в той форме
- при наличии более 2-х перечислейний лучше использовать список (про актуальность)
