### ISSUE TITLE
Редактирование персоны/проекта/задачи: доступно редактирование удаленной записи

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#55]
**Актуально** для формы редактирования проекта/задачи/персоны
**Шаги по воспроизведению:**

1. Открыть форму создания персоны
2. Нажать на кнопку "Добавить"
3. Заполнить все поля
4. Нажать на кнопку "Сохранить"
5. Нажать на кнопку "Изменить" для созданной записи
6. В открышемся окне нажать кнопку "Сохранить"
7. Удалить созданную запись
8. Нажать два раза кнопку назад в браузере
9. Обратить внимание на открывшуюся форму редактирования удаленного сотрудника

**Получено:**
Доступен переход в режим редактирования удаленной записи.

https://user-images.githubusercontent.com/88539537/207054698-68721242-bffd-45e0-956e-ab882a30816f.mp4

**Ожидаемо:**
Пользователь не может перейти в режим редактирования удаленной записи. Требование оговорено с куратором

**Comment by VKozlovskaya** [comment]
можно сократить заголовок до "доступно редактирование удаленной записи"

**Comment by VKozlovskaya** [comment]
актуальность не относится к шагам воспроизведения
