### ISSUE TITLE
Список проектов: грамматическая ошибка в названии колонки "Сокращённое название"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#6]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Проекты"
2.В списке проектов обратить внимание на название колонки "Сокращённое название"

**Получено:**
Отображается название колонки: СокращЕнное название
![ee](https://user-images.githubusercontent.com/88539537/205851275-0cc44b75-f2a8-439e-850c-dc36c7e02fbe.png)
**Ожидаемо:**
Отображается название колонки: "Сокращённое название".

**Comment by VKozlovskaya** [comment]
Картинка с демонстрацией дефекта расположена в ожидаемом результате, хотя показывает полученный.
