### ISSUE TITLE
Создание/Редактирование задачи: задача сохраняется при пустом обязательном поле "Исполнитель"

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#8]
**Шаги воспроизведения:**

1.В главном меню нажать на кнопку "Задачи"
2.В списке задач нажать на кнопку "Добавить"/"Изменить"
3.В форме создание/редактирование задачи заполнить все поля, кроме поля "Исполнитель"
4.Нажать на кнопку "Сохранить"

**Получено:**
Задача сохраняется
https://user-images.githubusercontent.com/88539537/205854890-7c8e3c96-ac32-4fe1-8de4-7283c39d39fb.mp4
**Ожидаемо:**
Появление валидационного сообщения "Не выбран исполнитель". См. спецификацию п.6 "Форма ввода задачи"

**Comment by VKozlovskaya** [comment]
см. коммент к дефекту 10
