### ISSUE TITLE
Список проектов/задач/персон: пагинация не отображается при создании записей

### ISSUE THREAD

**Issue by Aliaksei3** [Aliaksei3/Qulix#9]
**Предусловие**: должна быть создана минимум одна запись
**Шаги воспроизведения**:

1.В главном меню нажать на кнопку "Проекты/Задачи/Персоны"
2.В списке проектов/задач/персон нажать на кнопку "Добавить"
3.В форме создания проекта/задач/персон заполнить все поля формы
4.Нажать на кнопку "Сохранить"

**Получено:**
Не отображается пагинация
**![pag](https://user-images.githubusercontent.com/88539537/205859741-f7aad76c-4629-4e1c-b0e8-8dcd14a9e568.png)**

**Ожидаемо:**
Пагинация должна быть реализована

**Comment by VKozlovskaya** [comment]
см. коммент к дефекту 10

**Comment by VKozlovskaya** [comment]
У меня может не быть записей. Необходимо прописать предусловие
